### ISSUE TITLE
Undefined variable chunk_size in GraylogTcpHandler

### ISSUE THREAD

**Issue by drdivano** [severb/graypy#80]
https://github.com/severb/graypy/blob/d07d200ae8dfab5aa25b69c9a4a6a5cafa05b652/graypy/handler.py#L103

GraylogTcpHandler tries to pass chunk_size to the base class and fails with exception:

Traceback (most recent call last):
  File "/srv/cms/cms/afl/wsgi.py", line 22, in <module>
    application = get_wsgi_application()
  File "/srv/cms/cms-lib/django/core/wsgi.py", line 14, in get_wsgi_application
    django.setup()
  File "/srv/cms/cms-lib/django/__init__.py", line 20, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/srv/cms/cms-lib/django/utils/log.py", line 87, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'graylog-gelf': global name 'chunk_size' is not defined

**Comment by tusharmakkar08** [comment]
Hey @drdivano 

I think this was missed out. Will fix it asap. 

Thanks.
